In [1]:
import config_tf
from dataset import CardsWarper
from models import CardsEmbeding_v5
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
np.set_printoptions(precision=4, suppress=True)

2021-10-25 17:26:30.767020: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-25 17:26:30.767766: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-25 17:26:30.771648: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-25 17:26:30.772392: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-25 17:26:30.772721: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from S

2 Physical GPUs, 2 Logical GPUs


In [2]:
hand_size = 5
max_repeat = 5

embeding_size = 64
num_blocks = 2
num_heads = 2

In [3]:
wp = CardsWarper( 'cards.json' )

In [20]:
dec0 = ( np.random.uniform( 0, 1, [ 1, 164 ] ) * 53 ).astype(np.int32)
dec1 = np.array( [[ 1, 2, 3, 4, 5 ]] )
dec1a = np.array( [[ 3, 2, 5, 4, 1 ]] )
dec2 = np.array( [[ 4, 6, 5, 8, 7 ]] )
dec3 = np.array( [[ 1, 7, 8, 9, 10 ]] )
dec4 = np.array( [[ 10, 11, 14, 14 ]] )
dec5 = np.array( [[ 25, 28, 31 ]] )

In [5]:
with tf.device('/device:CPU:0'):

    model = model = CardsEmbeding_v5( 'test_v5_0', '/media/lucas/DADOS/saved/', 
                                      len(wp), embeding_size, hand_size, max_repeat, num_blocks, num_heads )
    model.load_training( 'saved/', model.m_name )
    
    o0, _, m0, freq0 = model.isin_op( dec0 )
    o1, _, m1, freq1 = model.isin_op( dec1 )
    o2, _, m2, freq2 = model.isin_op( dec2 )
    o3, _, m3, freq3 = model.isin_op( dec3 )
    o4, _, m4, freq4 = model.isin_op( dec4 )
    o5, _, m5, freq5 = model.isin_op( dec5 )





Loading from: saved/test_v5_0 ckp - 99900





In [6]:
p_counts = lambda vl: [ 'n:{} - c:{}'.format(a,b) for a, b in 
        zip( np.unique(vl[0], return_counts=True)[0], np.unique(vl[0], return_counts=True)[1] ) ]

indexes = lambda r: np.where( r > 0.7 )[0].tolist()
round_values = lambda r: [ int(x) if x - int(x) < 0.4 else int(x)+1 for x in r[ np.where( r > 0.7 ) ] ]

In [17]:
r = freq5[0,-1].numpy()

print("=====================")
print( dec1[0] )
print( dec2[0] )
print( dec3[0] )
print( dec4[0] )
print( dec5[0] )
print("=====================")
print( indexes( r ) )
print( round_values( r ) )
print( r )

[1 2 3 4 5]
[4 6 5 8 7]
[ 1  7  8  9 10]
[10 11 14 14]
[25 28 31]
[25, 28, 31]
[1, 1, 1]
[0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.9937 0.     0.     1.0253 0.
 0.     1.0944 0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.    ]


In [ ]:
r = freq0[0,-1].numpy()

print("=====================")
print( p_counts( dec0 ) )
print("=====================")
print( indexes( r ) )
print("=====================")
print( round_values( r ) )
print("=====================")
print( r )

In [ ]:
m = m0[:,0,...]
fig, axs = plt.subplots( 2, 2, figsize=( 20, 20 ) )

axs[0,0].imshow( m[0,0], cmap='gray', interpolation='nearest' )
axs[0,1].imshow( m[0,1], cmap='gray', interpolation='nearest' )
axs[1,0].imshow( m[1,0], cmap='gray', interpolation='nearest' )
axs[1,1].imshow( m[1,1], cmap='gray', interpolation='nearest' )

In [15]:
model.get_embeding( dec1 )[1][0,-1].numpy()

array([ -0.1739,  -8.8498,  -0.4601,  -0.3166,  -3.5017,   0.7583,
        -0.3367,   0.2276,   0.2976,  -1.4234,   0.5104,   0.1886,
        -0.0624,   0.0662,   2.3251, -23.7114,   0.5758,  -0.696 ,
         0.4684,   3.62  ,   0.2133,  -1.2574,   0.0342,  -0.8283,
         0.0582,  -9.2995,   0.4232,   1.0232,   0.254 ,   1.2774,
         0.8122,   0.3428,  15.589 ,  -0.3702,   0.4407,  -0.0486,
        -0.0278,  -0.146 ,  -1.5413,  -0.9049,  -0.6174,  -0.0666,
         0.2712,   0.0611,  -0.6579,   0.5815,   0.3724,  -0.063 ,
         0.1848,   0.1758,  -0.9264,   0.4893,  -0.0676,  -0.5105,
         0.0996,   0.2089,   0.3239,  -0.057 ,  -0.1876,  -0.1969,
         0.3996,  -0.3297,  -0.3387,  -0.4566], dtype=float32)

In [21]:
model.get_embeding( dec1a )[1][0,-1].numpy()

array([ -0.1558,  -8.6301,  -0.4704,  -0.2827,  -3.6201,   0.72  ,
        -0.3163,   0.2873,   0.292 ,  -1.3948,   0.5231,   0.1593,
        -0.0405,   0.0844,   2.3949, -23.4167,   0.5535,  -0.7221,
         0.4694,   3.5262,   0.2168,  -1.2338,   0.0516,  -0.8099,
         0.0553,  -9.642 ,   0.4304,   1.0484,   0.2744,   1.2447,
         0.8211,   0.3409,  15.2881,  -0.3164,   0.4234,  -0.0292,
        -0.0177,  -0.1525,  -1.5107,  -0.8664,  -0.628 ,  -0.0749,
         0.2804,   0.0852,  -0.6615,   0.5596,   0.371 ,  -0.0487,
         0.1787,   0.153 ,  -0.9491,   0.5215,  -0.0547,  -0.5019,
         0.1021,   0.1951,   0.6032,   0.1545,  -0.1637,  -0.2166,
         0.4303,  -0.3482,  -0.3383,  -0.4457], dtype=float32)