In [1]:
import config_tf
from dataset import CardsWarper
from models import CardsEmbeding_v5
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
np.set_printoptions(precision=4, suppress=True)

2021-10-25 16:41:49.588118: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-25 16:41:49.589531: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-25 16:41:49.594066: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-25 16:41:49.594958: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-25 16:41:49.595421: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from S

2 Physical GPUs, 2 Logical GPUs


In [2]:
hand_size = 5
max_repeat = 5

embeding_size = 64
num_blocks = 2
num_heads = 2

In [3]:
wp = CardsWarper( 'cards.json' )

In [4]:
dec0 = ( np.random.uniform( 0, 1, [ 1, 164 ] ) * 53 ).astype(np.int32)
dec1 = np.array( [[ 1, 2, 3, 4, 5 ]] )
dec2 = np.array( [[ 4, 6, 5, 8, 7 ]] )
dec3 = np.array( [[ 1, 7, 8, 9, 10 ]] )
dec4 = np.array( [[ 10, 11, 14, 14 ]] )
dec5 = np.array( [[ 25, 28, 31 ]] )

In [5]:
with tf.device('/device:CPU:0'):

    model = model = CardsEmbeding_v5( 'test_v5_0', '/media/lucas/DADOS/saved/', 
                                      len(wp), embeding_size, hand_size, max_repeat, num_blocks, num_heads )
    model.load_training( 'saved/', model.m_name )
    
    o0, _, m0, freq0 = model.isin_op( dec0 )
    o1, _, m1, freq1 = model.isin_op( dec1 )
    o2, _, m2, freq2 = model.isin_op( dec2 )
    o3, _, m3, freq3 = model.isin_op( dec3 )
    o4, _, m4, freq4 = model.isin_op( dec4 )
    o5, _, m5, freq5 = model.isin_op( dec5 )





Loading from: saved/test_v5_0 ckp - 99900





In [11]:
p_counts = lambda vl: [ 'n:{} - c:{}'.format(a,b) for a, b in 
        zip( np.unique(vl[0], return_counts=True)[0], np.unique(vl[0], return_counts=True)[1] ) ]

indexes = lambda r: np.where( r > 0.7 )[0].tolist()
round_values = lambda r: [ int(x) if x - int(x) < 0.4 else int(x)+1 for x in r[ np.where( r > 0.7 ) ] ]

In [13]:
r = freq4[0,-1].numpy()

print("=====================")
print( dec1[0] )
print( dec2[0] )
print( dec3[0] )
print( dec4[0] )
print( dec5[0] )
print("=====================")
print( indexes( r ) )
print( round_values( r ) )
print( r )

[1 2 3 4 5]
[4 6 5 8 7]
[ 1  7  8  9 10]
[10 11 14 14]
[25 28 31]
[10, 11, 14]
[1, 1, 2]
[0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.8016 0.8433 0.     0.     1.7911 0.     0.     0.     0.     0.
 0.     0.     0.0246 0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.0981 0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.    ]


In [14]:
r = freq0[0,-1].numpy()

print("=====================")
print( p_counts( dec0 ) )
print("=====================")
print( indexes( r ) )
print("=====================")
print( round_values( r ) )
print("=====================")
print( r )

['n:0 - c:4', 'n:1 - c:5', 'n:2 - c:1', 'n:3 - c:3', 'n:4 - c:7', 'n:5 - c:4', 'n:6 - c:5', 'n:7 - c:2', 'n:8 - c:9', 'n:9 - c:2', 'n:10 - c:3', 'n:11 - c:2', 'n:12 - c:1', 'n:13 - c:4', 'n:14 - c:4', 'n:15 - c:2', 'n:16 - c:4', 'n:17 - c:4', 'n:18 - c:3', 'n:19 - c:1', 'n:20 - c:5', 'n:21 - c:1', 'n:22 - c:3', 'n:23 - c:5', 'n:24 - c:3', 'n:25 - c:2', 'n:26 - c:3', 'n:27 - c:4', 'n:29 - c:3', 'n:30 - c:2', 'n:31 - c:2', 'n:33 - c:3', 'n:34 - c:7', 'n:35 - c:4', 'n:36 - c:3', 'n:37 - c:3', 'n:38 - c:3', 'n:39 - c:3', 'n:40 - c:3', 'n:41 - c:4', 'n:42 - c:5', 'n:43 - c:4', 'n:44 - c:3', 'n:45 - c:2', 'n:46 - c:3', 'n:47 - c:2', 'n:48 - c:3', 'n:50 - c:1', 'n:51 - c:2', 'n:52 - c:3']
[0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 29, 30, 31, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 51, 52]
[3, 4, 2, 5, 3, 4, 1, 6, 1, 2, 2, 3, 3, 1, 3, 3, 2, 1, 3, 1, 2, 4, 2, 2, 2, 3, 2, 2, 1, 2, 4, 3, 2, 2, 2, 2, 2, 3, 4, 3, 2, 2, 2,

In [ ]:
m = m0[:,0,...]
fig, axs = plt.subplots( 2, 2, figsize=( 20, 20 ) )

axs[0,0].imshow( m[0,0], cmap='gray', interpolation='nearest' )
axs[0,1].imshow( m[0,1], cmap='gray', interpolation='nearest' )
axs[1,0].imshow( m[1,0], cmap='gray', interpolation='nearest' )
axs[1,1].imshow( m[1,1], cmap='gray', interpolation='nearest' )