In [1]:
import config_tf
from dataset import CardsWarper
from models import CardsEmbeding_v2
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from dataset import sets_tasks_v2

2 Physical GPUs, 2 Logical GPUs


2021-10-22 10:31:32.494710: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-22 10:31:32.496149: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-22 10:31:32.501990: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-22 10:31:32.503414: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-22 10:31:32.504066: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from S

In [4]:
hand_size = 5
max_repeat = 5

embeding_size = 64
num_blocks = 2
num_heads = 2

In [5]:
wp = CardsWarper( 'cards.json' )

In [69]:
dec1 = np.array( [[ 1, 2, 3, 4, 5 ]] )
dec2 = np.array( [[ 4, 6, 5, 8, 7 ]] )
dec3 = np.array( [[ 1, 7, 8, 9, 10 ]] )
dec4 = np.array( [[ 10, 11, 14, 14 ]] )
dec5 = np.array( [[ 25, 28, 31 ]] )

In [70]:
with tf.device('/device:CPU:0'):

    model = model = CardsEmbeding_v2( 'test_v2_1', 'saved/', len(wp), embeding_size, hand_size, max_repeat, num_blocks, num_heads )
    model.load_training( 'saved/', model.m_name )
    
    o1, _, a1, m1 = model( dec1 )
    o2, _, a2, m2 = model( dec2 )
    o3, _, a3, m3 = model( dec3 )

    e1 = model.get_embeding_eval( dec1 )
    e2 = model.get_embeding_eval( dec2 )
    e3 = model.get_embeding_eval( dec3 )
    e4 = model.get_embeding_eval( dec4 )
    e5 = model.get_embeding_eval( dec5 )
    
    print( np.argmax( o1, -1 )[0][-1][dec1] )
    print( np.argmax( o2, -1 )[0][-1][dec2] )
    print( np.argmax( o3, -1 )[0][-1][dec3] )




Loading from: saved/test_v2_1



[[1 1 1 1 1]]
[[1 1 1 1 1]]
[[1 1 1 1 1]]


In [59]:
with tf.device('/device:CPU:0'):
    op1 = e1 - e2
    _, _, _, erm1 = model.reconstruct_eval( tf.expand_dims( op1, 1 ) )
    r1 = erm1.numpy()[0][0]
    
print(dec1[0])
print(dec2[0])
print( np.where( r1 ) )

[1 2 3 4 5 7 8]
[4 6 5 8 7]
(array([1, 2, 3]),)


In [66]:
with tf.device('/device:CPU:0'):
    op1 = e2 - e3   
    _, _, _, erm1 = model.reconstruct_eval( tf.expand_dims( op1, 1 ) )
    r1 = erm1.numpy()[0][0]
    
print(dec3[0])
print(dec4[0])
print( np.where( r1 ) )

[ 7  8  9 10]
[10 11 14 14]
(array([4, 5, 6]),)


In [71]:
with tf.device('/device:CPU:0'):
    op1 = ( e1 - e2 ) - e3
    _, _, _, erm1 = model.reconstruct_eval( tf.expand_dims( op1, 1 ) )
    r1 = erm1.numpy()[0][0]
    
print(dec1[0])
print(dec2[0])
print(dec3[0])
print(dec4[0])
print( np.where( r1 ) )

[1 2 3 4 5]
[4 6 5 8 7]
[ 1  7  8  9 10]
[10 11 14 14]
(array([2, 3]),)


In [ ]:
m = m1[:,0,...]
fig, axs = plt.subplots( 2, 2, figsize=( 10, 10 ) )

axs[0,0].imshow( m[0,0], cmap='gray', interpolation='nearest' )
axs[0,1].imshow( m[0,1], cmap='gray', interpolation='nearest' )
axs[1,0].imshow( m[1,0], cmap='gray', interpolation='nearest' )
axs[1,1].imshow( m[1,1], cmap='gray', interpolation='nearest' )

In [2]:
data = np.array( [ [ 1, 2, 3, 4, 5 ], [ 3, 4, 5, 6, 7 ] ] )
_, _, _, ym = sets_tasks_v2(data, 5, 53, 2 )
ym

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0.],
    