In [1]:
import config_tf
from dataset import CardsWarper
from models import CardsEmbeding
import numpy as np
import tensorflow as tf

2 Physical GPUs, 2 Logical GPUs


2021-10-20 13:08:40.536380: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-20 13:08:40.537715: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-20 13:08:40.543524: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-20 13:08:40.544657: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-10-20 13:08:40.545414: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from S

In [2]:
hand_size = 6
max_repeat = 5
embeding_size = 32
num_blocks = 4
num_heads = 4

In [3]:
wp = CardsWarper( 'cards.json' )

In [10]:
dec1 = ( np.random.uniform( 0, 1, [ 1, hand_size ] ) * ( len( wp ) ) ).astype( np.int32 )
dec2 = ( np.random.uniform( 0, 1, [ 1, hand_size ] ) * ( len( wp ) ) ).astype( np.int32 )
dec3 = ( np.random.uniform( 0, 1, [ 1, hand_size ] ) * ( len( wp ) ) ).astype( np.int32 )

In [12]:
with tf.device('/device:CPU:0'):

    model = CardsEmbeding( 'test6', 'logs', len(wp), embeding_size, hand_size, max_repeat, num_blocks, num_heads )
    model.load_training( 'saved/', model.m_name )
    
    o1, m1 = model( dec1 )
    o2, m2 = model( dec2 )
    o3, m3 = model( dec3 )

    e1 = model.get_embeding( dec1 )
    e2 = model.get_embeding( dec2 )
    e3 = model.get_embeding( dec3 )
    
    print( np.argmax( o1, -1 )[0][-1][dec1] )
    print( np.argmax( o2, -1 )[0][-1][dec2] )
    print( np.argmax( o3, -1 )[0][-1][dec3] )




Loading from: saved/test6



[[1 1 1 1 1 1]]
[[1 1 1 1 1 1]]
[[1 1 1 1 1 1]]


In [27]:
with tf.device('/device:CPU:0'):
    op = e1 * e2
    e3, e3m = model.reconstruct( op )
    r = e3m.numpy()[0]

print(dec1)
print(dec2)
print(dec3)
print( np.where( r ) )

[[16  9 40 43  2 50]]
[[47 14 25  4 42 43]]
[[30  6 19 48 11 28]]
(array([ 1,  3,  4,  7, 13, 14, 15, 16, 27, 41, 42, 43]),)
